### PR TITLE
added support for extended colors (xterm 256 and 24 bit rgb)

### PR DESCRIPTION
**Pull request by Joe-Merten**
This PR adds support for extended color like `esc[38;5;<index>m` or `esc[38;2;<r>;<g>;<b>m` when parsing.
Need this to implement extended color support in [jenkins-ansicolor-plugin](https://github.com/dblock/jenkins-ansicolor-plugin/). See also [#89](https://github.com/dblock/jenkins-ansicolor-plugin/issues/89) and [#96](https://github.com/dblock/jenkins-ansicolor-plugin/pull/96).

### CODE REVIEW

**Comment by ssbarnea** [comment]
Can we have this reviewed and merged?

**Comment by ssbarnea** [comment]
@gnodet Thank you! I performed a new build of jenkins-ansicolor-plugin and tested it and I can confirm that this patch fixed it. Now we only need 1.15 to be released so we can officially consume it.

**Comment by ssbarnea** [comment]
@gnodet or @hboutemy Can we have a 1.15 released? I cannot make an official build that uses a git branch of jansi. I did this for testing, worked really well, time to get 1.15 jar uploaded to maven.

**Comment by hboutemy** [comment]
before releasing JAnsi 1.15, I'd like to enhance HawtJNI first: https://issues.apache.org/jira/browse/MNG-6186
I'll provide a PR soon

**Comment by gnodet** [comment]
Sorry, I missed your latest comment.  Jansi 1.15 has been released, but let me know in case you need a new release.

**Comment by hboutemy** [comment]
releases are cheap: no big issue, better to have a release now than a promise to do it later
I'll keep you informed
notice: you don't seem to track milestones with GitHub issue tracker, is it intended? It would be easy and useful to track what goes into each release

**Comment by hboutemy** [comment]
https://github.com/fusesource/hawtjni/pull/35 created

**Pull request merged**
