### PR TITLE
Fix FFM backend on Windows

### PR DESCRIPTION
**Pull request by Glavo**
The FFM backend appears to be untested and will crash when using it, I'm trying to solve these problems.

* Avoid lookup `ioctl` and `isatty` on Windows;
* Make `SYMBOL_LOOKUP` initialized earlier to avoid NPE
* Fix wrong alignment;
* Load Kernel32;
* Fix incorrect type conversion;
* Impl CLibrary for Windows;
* Fix string encoding;

There are more issues waiting to be fixed, WIP.

### CODE REVIEW

**Comment by Glavo** [comment]
It no longer crashes, but some features still don't work.

**Comment by Glavo** [comment]
It mostly works now, but I suspect there are hidden bugs that will need to be fixed.

**Comment by Glavo** [comment]
This PR is ready for review.

@gnodet I think it would be better to move `AnsiConsoleSupport` and `org.fusesource.jansi.ffm` to `org.fusesource.jansi.internal`?

They are the same low-level API as the existing `CLibrary`/`Kernel32` and do not seem to be suitable as part of the public API.

I'd like to do some refactoring before they are officially released, what do you think?

**Comment by gnodet** [comment]
> This PR is ready for review.
> 
> @gnodet I think it would be better to move `AnsiConsoleSupport` and `org.fusesource.jansi.ffm` to `org.fusesource.jansi.internal`?
> 
> They are the same low-level API as the existing `CLibrary`/`Kernel32` and do not seem to be suitable as part of the public API.
> 
> I'd like to do some refactoring before they are officially released, what do you think?

Yes, that makes sense.

**Comment by Glavo** [comment]
> > This PR is ready for review.
> > @gnodet I think it would be better to move `AnsiConsoleSupport` and `org.fusesource.jansi.ffm` to `org.fusesource.jansi.internal`?
> > They are the same low-level API as the existing `CLibrary`/`Kernel32` and do not seem to be suitable as part of the public API.
> > I'd like to do some refactoring before they are officially released, what do you think?
> 
> Yes, that makes sense.

Okay, when this PR is merged, I will do this work in a new PR.

**Pull request merged**
