### PR TITLE
Fix windows-arm64 DLL name

### PR DESCRIPTION
**Pull request by gnodet**
- **Rebuild libraries**
- **Fix windows-arm64 DLL name**

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by michael-o** [comment]
@gnodet Please merge this.

**Comment by Friendseeker** [comment]
@gnodet Would it be possible to publish Jansi 2.4.2 containing the fix?

I am working with [Alexandre Archambault](https://github.com/alexarchambault) to improve Windows ARM support for [coursier](https://github.com/coursier/coursier) & [mill](https://github.com/com-lihaoyi/mill). We encountered this issue since both depends on Jansi.

c.c. @alexarchambault

**Comment by slawekjaranowski** [comment]
@gnodet 
As I see it can resolve https://issues.apache.org/jira/browse/MNG-8170

Can you release?

**Comment by gnodet** [comment]
> @gnodet As I see it can resolve https://issues.apache.org/jira/browse/MNG-8170
> 
> Can you release?

Done

**Pull request merged**
